<?php
define("_CREATE_ACCOUNT", "खाता बनाएं");
define("_CREATE_N_ACCOUNT", "नया खाता बनाएँ");
define("_FULLNAME", "पूरा नाम");
define("_USERNAME", "उपयोगकर्ता नाम");
define("_EMAIL", "ईमेल");
define("_PASSWORD", "कुंजिका");
define("_CPASSWORD", "पासवर्ड की पुष्टि कीजिये");
define("_BY_CLICKING_SIGNUP_STR", "खाता बनाएं पर क्लिक करके, आप हमारे लिए सहमत हैं");
define("_LOGIN", "लॉग इन ");
define("_SIGNUP", "साइन इन ");
define("_MALE", "पुरुष");
define("_FEMALE", "महिला");
define("_TERM", "टर्म");
define("_PRIVACY", "गोपनीयता नीति");
define("_AND", "तथा");
define("_COOKIE", "कुकी का उपयोग");
define("_ALREADY_HAVE_AN_ACCOUNT", "पहले से ही एक खाता है");
define("_LOGIN_NOW", "अब प्रवेश करें");
define("_FOR_FREE", "मुक्त करने के लिए");
define("_SELECT_LANGUAGE", "भाषा का चयन करें ");
define("_FORGOT_A_PASSWORD", "पासवर्ड भूल गए हैं?");
define("_DONT_HAVE_A_ACCOUNT", "खाता नहीं है? ");
define("_MY_PHOTOS", "My photos");
define("_MY_VIDEOS", "My videos");
define("_SETTING", "समायोजन");
define("_LANGUAGE", "भाषा");
define("_MYNOTEPAD", "मेरा नोटपैड");
define("_NEW_NOTE", "नया नोट");
define("_SEE_ALL_NOTES", "सभी नोट देखें");
define("_RECENTLY_STARTS_FROM", "Recently starts from :");
define("_MORE", "अधिक");
define("_SAVE_POSTS", "सहेजे गए पोस्ट्स");
define("_SUPPORT_BOX", "सपोर्ट  बॉक्स");
define("_REPORT_A_PROBLEM", "समस्या के बारे में बताएं");
define("_LOGOUT", "लॉग आउट");
define("_WRITE","लिखना");
define("_VIDEO","वीडियो");
define("_TITLE","शीर्षक");
define("_AUDIOS","ऑडियो");
define("_AUDIO","ऑडियो");
define("_POLLS","पोल");
define("_PHOTO","फ़ोटो");
define("_FOR_YOU","फॉर यू");
define("_PUBLIC","सार्वजनिक");
define("_FOLLOWERS","फोल्लोवेर्स");
define("_ONLY_ME","केवल मैं");
define("_THUMBNAIL","thumbnail");
define("_SHARE_POST_AND_IDEA_IN_OUR_COMMUNITY","हमारे समुदाय के साथ अपने विचारों को साझा करें, पोस्ट करें");
define(" _WRITE_OPTIONAL","अपनी पोस्ट के लिए एक शीर्षक लिखें (वैकल्पिक)");
define("_FOR YOU","तुम्हारे लिए");
define("_FOLLOWING","फोल्लोविंग");
define("_HOME","होम");
define("_SEARCH","खोजें");
define("_NOTIFICATION","अधिसूचना");
define("_DONE","done");
define("_ENTER_USERNAME","लॉगिन करने के लिए अपना उपयोगकर्ता नाम दर्ज करें");
define("ENTERPASSWORD","लॉगिन करने के लिए अपना पासवर्ड डालें");
/*define("_VERIFIED","सत्यापित पेज");*/
define("_FILL_REQUIRED_FIELDS","कृपया आवश्यक फ़ील्ड भरें");
define("_EMAIL_EXISTS","ईमेल पता पहले से मौजूद है");
define("_PASSWORD_SHORT","आपका पासवर्ड कम से कम छः अक्षरों का होना चाहिए। कृपया दूसरा प्रयास करें");
define("_PASSWORD_NOT_MATCH","आपका पासवर्ड पुष्टि क्षेत्र से मेल नहीं खाता है");
define("_INVALID_EMAIL","अमान्य ईमेल पता");
define("_SPECIAL_CHARACTERS_NOT_ALLOWD","विशेष वर्णों की अनुमति नहीं है");
define("_USERNAME_SHOULD_IN_ENGLISH","उपयोगकर्ता नाम अंग्रेजी में होना चाहिए");
define("_ONLY_ALLOWED","केवल (_) शब्दों के बीच की अनुमति है");
define("_NUMBER_LATTER_ALLOWED","संख्या और अक्षर की अनुमति है");
define("_WHITE_SPACE_NOT_ALLOWED","शब्दों के बीच सफेद रिक्त स्थान की अनुमति नहीं है");
define("_ERROR_IN_USERNAME","उपयोगकर्ता नाम में त्रुटि");
define("_USERNAME_NOT_EXIST","उपयोगकर्ता नाम मौजूद नहीं है! कोई उपयोगकर्ता नाम जो आपने दर्ज किया है");
define("_FRIENDS","दोस्त");
define("_REQUEST","अनुरोध");
define("_COUNTINUE_READING","पढ़ना जारी रखें");
define("_YOU_CAN_NOT_LOGIN","अब आप लॉगिन नहीं कर सकते! प्रतीक्षा (15 मिनट) और फिर कोशिश करें");
define("_USERNAME_EMAIL_NOT_EXIST","उपयोगकर्ता नाम या ईमेल मौजूद नहीं है");
define("_USERNAME_EXIST","उपयोगकर्ता नाम पहले से मौजूद है!");
define("_USER_PASSWORD","उपयोगकर्ता और पासवर्ड गलत है");
define("_ATTEMPTS_LOGIN","लॉगिन करने का प्रयास");
define("_USER_PASSWORD_INCORRECT","उपयोगकर्ता का पासवर्ड गलत है! आपके पास");
define("_WELCOME","स्वागत हे");
define("_LOADING","लोड हो रहा है");
define("_EDIT_PROFILE","प्रोफ़ाइल एडिट करें");
define("_POST_NOW","अभी पोस्ट करें");
define("_FOLLOW","फॉलो");
define("_NO_MORE_STORIES","No more stories");
define("_LOAD_MORE","Load more");
define("_SHARED_A_POST","एक पोस्ट साझा की");
define("_COMMENTS","टिप्पणियाँ");
define("_SHARES","शेयर");
define("_EDIT_POST","एडिट पोस्ट");
define("_DELET_POST"," पोस्ट हटाएं");
define("_REPORT_POST","रिपोर्ट पोस्ट");
define("_SAVE_POST","सहेजें पोस्ट");
define("_WRITE_POST_TITLE","अपनी पोस्ट के लिए एक शीर्षक लिखें (वैकल्पिक))");
define("_SAVE","सहेजें");
define("_CANCEL","रद्द");
define("_CONTINUE_READING","पढ़ना जारी रखें");
define("_COMMENT","टिप्पणी");
define("_SHARE","शेयर");
define("_YOU_LIKED_THIS","आपको यह पसंद आया");
define("_LIKE","पसंद");
define("_BE_THE_FIRST","पहले रहो");
define("_SHARE_NOW","अब साझा करें");
define("_WRITE_COMMENT","टिप्पणी लिखें ...");
define("_NEW_LINE","नई लाइन &xrarr");
define("_PLEASE_WAIT","कृपया प्रतीक्षा करें...");
define("_POSTING","पोस्टिंग");
define("_EDITED","एडिटेड");
define("_EDIT_COMMENT","टिप्पणी एडिट करें");
define("_DELET_COMMENT","टिप्पणी हटाएं");
define("_POSTING_SAVED","पोस्ट सहेजा गया");
define("_SAVED_POST_BEFORE","आपने पहले इस पोस्ट को बचाया!");
define("_DO_YOU_WANT_TO_DELET_THIS","क्या आप इसे हटाना चाहते हैं?");
define("_YOU_CAN_NOT_UNDO_THIS_AFTER_DELETING_IT","इसे हटाने के बाद आप इसे पूर्ववत नहीं कर सकते");
define("_POSTSHARED","आपकी टाइमलाइन पर पोस्ट साझा की गई।");
define("_ERROR_OCCRRED","त्रुटि, एक त्रुटि हुई! बाद में पुन: प्रयास करें।");
define("_POST_REPORT","पोस्ट की रिपोर्ट! हम जल्द ही आपकी रिपोर्ट की समीक्षा करेंगे");
define("_YOU","आप");
define("_NOTHING_SHOW","दिखाने के लिए कुछ भी नहीं");
define("_NOTHINGSHOW","दिखाने के लिए कुछ भी नहीं");
define("_BIO","बायो");
define("_EMPTY_CHAT","इस चैट में आपके पास कोई संदेश नहीं है .. हैलो बोलें अब चैटिंग शुरू करें");
define("_ACTIVE_NOW","अब सक्रिय");
define("_NOT_ACTIVE","अक्रिय");
define("_REPORT_COMMENT","रिपोर्ट टिप्पणी");
define("_LIKED_YOUR_POST","आपकी पोस्ट पसंद आई");
define("_SHARED_YOUR_POST","अपनी पोस्ट साझा की");
define("_STARTING_FOLLOWING_YOU","आपको फोलो करना शुरू किया");
define("_COMMENT_ON_YOUR_POST","आपकी पोस्ट पर टिप्पणी की");
define("_YOU_GOT_NEW_STAR","You got new star from");
define("_MINUTES_AGO","मिनट");
define("_HOURS_AGO","घंटे");
define("_DAY_AGO","दिन");
define("_DAYS_AGO","दिन");
define("_WEEK_AGO","सप्ताह");
define("_WEEKS_AGO","सप्ताह");
define("_MONTH_AGO","महीना");
define("_MONTHS_AGO","महीने");
define("_YEAR_AGO","साल");
define("_YEARS_AGO","वर्षों");
define("_JUST_NOW","अभी");
define("_HOUR_AGO","घंटा");
define("_MINUTE_AGO","मिनट");
define("_About","के बारे में");
define("_STUDIES","में पढ़ता है");
define("_WORKING","काम कर रहे");
define("_AT","पर");
define("_LIVES_IN","में रहता है");
define("_BORN_0N","पर पैदा हुआ");
define("_SEE_THIS","केवल आप इसे देख सकते हैं");
define("_YOUR_FOLLOWER","आपके  फोल्लोवेर्स");
define("_FOLLOWERS_TITLE","फोल्लोवेर्स");
define("_PEOPLE_WHO_YOU_R_FOLLOWING","जिन लोगों को आप फॉलो कर रहे हैं");
define("_HE","वह");
define("_SHE","वह");
define("_PEOPLE_THAT","लोग जो");
define("_ARE_FOLLOWING","फोल्लोवेर्स कर रहे हैं");
define("_YOU_HAVE_NOT_POSTING_ANYTHING","आपने अभी तक कुछ भी पोस्ट नहीं किया है");
define("_YOU_HAVE_NOT_POSTING_ANYTHING_IMAGE","आपने अभी तक कुछ भी तस्वीर पोस्ट नहीं की है");
define("_YOU_HAVE_NOT_POSTING_ANYTHING_VIDEO","आपने अभी तक कुछ भी वीडियो पोस्ट नहीं किया है");
define("_YOU_HAVE_NOT_POSTING_ANYTHING_AUDIO","आपने अभी तक कुछ भी ऑडियो पोस्ट नहीं किया है");
define("_HAS_NOT_POSTED_ANYTHING","अभी तक कुछ भी पोस्ट नहीं किया है");
define("_HAS_NOT_POSTED_ANYTHING_IMAGE","अभी तक कुछ भी  तस्वीर पोस्ट नहीं किया है");
define("_HAS_NOT_POSTED_ANYTHING_VIDEO","अभी तक कुछ भी  वीडियो पोस्ट नहीं किया है");
define("_HAS_NOT_POSTED_ANYTHING_AUDIO","अभी तक कुछ भी  ऑडियो पोस्ट नहीं किया है");
define("_SORRY_THIS_PAGE_NOT_AVAILABLE","क्षमा करें, यह पृष्ठ उपलब्ध नहीं है");
define("_PROFILE_PAGE_NOT_FOUND","क्षमा करें कि यह पृष्ठ हटा दिया गया है, या वह पृष्ठ मौजूद नहीं है!");
define("_GO_BACK_PREVIOUS_PAGE","पिछले पेज पर वापस जाओ");
define("_navbar_ph","खोजें..");
define("_PUBLIC_POSTS","सार्वजनिक पोस्ट");
define("_ADVANCED_POSTS","उन्नत खोजें");
define("_SEARCH_MORE_ABOUT","के बारे में अधिक खोज करें");
define("_NOT_FOUND","नहीं मिला");
define("_NO_USERS_LIKE_THE_NAME_YOU_ENTERED","आपके द्वारा दर्ज नाम जैसा कोई उपयोगकर्ता नहीं है");
define("_Notification","सूचनाएं");
define("_NO_NOTIFICATIONS","कोई सूचनाएं नहीं");
define("_SEE_ALL","सभी देखें");
define("_MESSAGES","संदेश");
define("_SELET_TO_CHAT","संदेश भेजने के लिए कृपया चैट का चयन करें");
define("_WRITE_MESSAGE","एक सन्देश लिखिए..");
define("_USER_PROFILE","उपयोगकर्ता प्रोफ़ाइल");
define("_CURRENT_PASSWORD_INCORRECT","मौजूदा पासवर्ड गलत है");
define("_PLZ_FILL_REQURIED_FIELDS","कृपया आवश्यक फ़ील्ड भरें");
define("_NEW_PASSWORD_NOT_MATCH","नया पासवर्ड फ़ील्ड पुष्टि फ़ील्ड से मेल नहीं खाता है");
define("_CHANGE_PASSWORD_SAVE","परिवर्तन सुरक्षित रूप से सहेजे गए");
define("_ERROR_SOMTHING_WORNG","त्रुटि, एक त्रुटि हुई! बाद में पुन: प्रयास करें।");
define("_GENERAL","सामान्य");
define("_EDUCATION","शिक्षा");
define("_WORK","काम");
define("_CONTRY","देश");
define("_SELECT_COUNTRY","अपने देश का चयन करें");
define("_BIRTHDAY","जन्मदिन");
define("_WEBSITE","वेबसाइट");
define("_CURRENT_PASSWORD","वर्तमान पासवर्ड");
define("_SAVE_CHANGE","परिवर्तनों को सुरक्षित करें");
define("_FULL_NAME","पूरा नाम");
define("_REQURIED","आवश्यक");
define("_EMAIL_ADDRESS","ईमेल पता");
define("_NEW_PASSWORD","नया पासवर्ड");
define("_CONFIRM_NEW_PASSWORD","पासवर्ड की पुष्टि कीजिये");
define("_GENDER","लिंग");
define("_DELET","हटाएं");
define("_NOTPAD_MAIN_TITLE","अपने गुप्त पासवर्ड, कोड, नोट्स, लिंक और सब कुछ ऑनलाइन सहेजें .. बस आप इसे देख या संपादित कर सकते हैं");
define("_NEW_NOTE_P","नया गुप्त नोट बनाएं, केवल आप इसे देख और संपादित कर सकते हैं");
define("_NOTE_TITLE","नोट शीर्षक");
define("_NOTE_CONTENT","नोट सामग्री");
define("_CREATE","क्रिएट");
define("_ALL_POST_SAVED","सभी पोस्ट जो आपने सहेजे हैं");
define("_NOTHING_SAVED_YET","अभी तक कुछ भी नहीं बचा");
define("_CLICK_TO_VIEW_YOUR_REPORT","अपनी रिपोर्ट देखने के लिए क्लिक करें");
define("_YOUR_REPORT","आपकी रिपोर्ट");
define("_HELP_US_TO_MAKE_OUR_COMMUNITY","हमारे समुदाय को बेहतर बनाने में हमारी मदद करें");
define("_YOUR_FEEDBACK_HELPS_US_IMPROVE_OUR_COMMUNITY","आपकी प्रतिक्रिया से हमें अपने समुदाय को बेहतर बनाने में मदद मिलती है");
define("_SUBJECT","विषय");
define("_SUBMIT","प्रस्तुत");
define("_REPLAY","Replay");
define("_THIS_PAGE_NOT_AVAILABLE","क्षमा करें, यह पृष्ठ उपलब्ध नहीं है");
define("_THIS_PAGE_NOT_AVAILABLE2","क्षमा करें कि यह पृष्ठ हटा दिया गया है, या वह पृष्ठ मौजूद नहीं है!");
define("_THIS_PAGE_NOT_AVAILABLE3","पिछले पेज पर वापस जाओ");
define("_OPEN","ओपन");
define("_CLOSED","बन्द");
define("_YOU_ANONYMOUSLY_REPORTED","आपने गुमनाम रूप से सूचना दी थी");
define("_POST","पोस्ट");
define("_UPLOAD","अपलोड");
define("_HASHTAG_NOT_AVAILABLE","हैशटैग उपलब्ध नहीं!");
define("_NEWS","समाचार");
define("_tv","टीवी");
define("_STORE","स्टोर");
define("_NEW","नया");
define("_JOB","जॉब");
define("_WORK_TITLE","काम का शीर्षक");
define("_WORK_PLACE","कार्यस्थल");
define("_COMMENT_ON_THIS_POST","इस पोस्ट पर टिप्पणी करें.");
?>