<?php
define("_CREATE_ACCOUNT", "Create account");
define("_CREATE_N_ACCOUNT", "Create new account");
define("_WELCOME_TO_USER","Welcome to Users");
define("_FULLNAME", "fullname");
define("_USERNAME", "Username");
define("_EMAIL", "Email");
define("_PASSWORD", "Password");
define("_CPASSWORD", "Confirm password");
define("_BY_CLICKING_SIGNUP_STR", "By clicking Create account, you agree to our");
define("_LOGIN", "Login");
define("_SIGNUP", "Signin");
define("_MALE", "Male");
define("_FEMALE", "Female");
define("_TERM", "term");
define("_PRIVACY", "Privacy policy");
define("_AND", "and");
define("_COOKIE", "Cookie use");
define("_ALREADY_HAVE_AN_ACCOUNT", "Already have an account");
define("_LOGIN_NOW", "Login now");
define("_FOR_FREE", "for free");
define("_SELECT_LANGUAGE", "Select Language ");
define("_LANGUAGE_CHOOSE","Select Language ");
define("_FORGOT_A_PASSWORD", "Forgot your password?");
define("_DONT_HAVE_A_ACCOUNT", "Don't have an account? ");
define("_MY_PHOTOS", "My photos");
define("_MY_VIDEOS", "My videos");
define("_SETTING", "Settings");
define("_LANGUAGE", "Language");
define("_MYNOTEPAD", "My notepad");
define("_NEW_NOTE", "New note");
define("_SEE_ALL_NOTES", "See all notes");
define("_RECENTLY_STARTS_FROM", "Recently starts from :");
define("_MORE", "More");
define("_SAVE_POSTS", "Saved posts");
define("_SUPPORT_BOX", "Support box");
define("_REPORT_A_PROBLEM", "Report a problem");
define("_LOGOUT", "Logout");
define("_WRITE","Write");
define("_VIDEO","video");
define("_TITLE","title");
define("_AUDIOS","Audios");
define("_AUDIO","audio");
define("_POLLS","Polls");
define("_PHOTO","Photo");
define("_PUBLIC","Public");
define("_FOLLOWERS","Followers");
define("_ONLY_ME","Only me");
define("_THUMBNAIL","thumbnail");
define("_SHARE_POST_AND_IDEA_IN_OUR_COMMUNITY","Share, post your ideas with our community");
define(" _WRITE_OPTIONAL","Write a title to your post (optional)");
define("_FOR_YOU","For you");
define("_FOLLOWING","Following");
define("_HOME","Home");
define("_SEARCH","Search");
define("_NOTIFICATION","Notification");
define("_DONE","done");
define("_ENTER_USERNAME","Enter your username to login");
define("ENTERPASSWORD","Enter your password to login");
define("_VERIFIED","Verified page");
define("_FILL_REQUIRED_FIELDS","Please fill required fields");
define("_EMAIL_EXISTS","Email address already exist");
define("_PASSWORD_SHORT","Your password must be at least 6 characters long. Please try another");
define("_PASSWORD_NOT_MATCH","Your password does not match with confirm field");
define("_INVALID_EMAIL","Invalid email address");
define("_SPECIAL_CHARACTERS_NOT_ALLOWD","Special characters not allowed");
define("_USERNAME_SHOULD_IN_ENGLISH","Username should be in English");
define("_ONLY_ALLOWED","Only ( _ ) allowed between words");
define("_NUMBER_LATTER_ALLOWED","Numbers and letters are allowed");
define("_WHITE_SPACE_NOT_ALLOWED","White spaces not allowed between words");
define("_ERROR_IN_USERNAME","Error in username");
define("_USERNAME_NOT_EXIST","User name not exists! No User name like that you entered");
define("_FRIENDS","Friedns");
define("_REQUEST","Requests");
define("_COUNTINUE_READING","Continue reading");
define("_YOU_CAN_NOT_LOGIN","You can not login now! wait (15 min) and try again");
define("_USERNAME_EMAIL_NOT_EXIST","Username or email not exist");
define("_USERNAME_EXIST","Username is already exist!");
define("_USER_PASSWORD","User and password incorrect");
define("_ATTEMPTS_LOGIN","attempts to login");
define("_USER_PASSWORD_INCORRECT","User password incorrect! You have");
define("_WELCOME","Welcome");
define("_LOADING","Loading");
define("_EDIT_PROFILE","Edit profile");
define("_POST_NOW","Post now");
define("_FOLLOW","Follow");
define("_NO_MORE_STORIES","No more stories");
define("_LOAD_MORE","Load more");
define("_SHARED_A_POST","Shared a post");
define("_COMMENTS","comments");
define("_SHARES","shares");
define("_EDIT_POST","Edit post");
define("_DELET_POST","Delete post");
define("_REPORT_POST","Report post");
define("_SAVE_POST","Save post");
define("_WRITE_POST_TITLE","Write a title to your post (optional)");
define("_SAVE","save");
define("_CANCEL","cancel");
define("_CONTINUE_READING","Continue reading");
define("_COMMENT","Comment");
define("_SHARE","Share");
define("_YOU_LIKED_THIS","You liked this");
define("_LIKE","Like");
define("_BE_THE_FIRST","Be the first");
define("_SHARE_NOW","Share now");
define("_WRITE_COMMENT","Write a comment ...");
define("_NEW_LINE","New line &xrarr;");
define("_PLEASE_WAIT","Please wait...");
define("_POSTING","Posting");
define("_EDITED","Edited");
define("_EDIT_COMMENT","Edit comment");
define("_DELET_COMMENT","Delete comment");
define("_POSTING_SAVED","Post Saved");
define("_SAVED_POST_BEFORE","You saved this post before!");
define("_DO_YOU_WANT_TO_DELET_THIS","Do you want to delete this?");
define("_YOU_CAN_NOT_UNDO_THIS_AFTER_DELETING_IT","You can not undo this after deleting it");
define("_POSTSHARED","Post shared on your timeline.");
define("_ERROR_OCCRRED","Error, An error occurred! Please try again later.");
define("_POST_REPORT","Post reported! we will review your report soon");
define("_YOU","You");
define("_NOTHING_SHOW","Nothing to show");
define("_NOTHINGSHOW","Nothing to show");
define("_BIO","Bio");
define("_EMPTY_CHAT","You have no messages in this chat .. say hello to start chatting now");
define("_ACTIVE_NOW","Active now");
define("_NOT_ACTIVE","Not Active");
define("_REPORT_COMMENT","Report comment");
define("_LIKED_YOUR_POST","liked your post");
define("_SHARED_YOUR_POST","shared your post");
define("_STARTING_FOLLOWING_YOU","started following you");
define("_COMMENT_ON_YOUR_POST","commented on your post");
define("_YOU_GOT_NEW_STAR","You got new star from");
define("_MINUTES_AGO","minutes");
define("_HOURS_AGO","hours");
define("_DAY_AGO","day");
define("_DAYS_AGO","days");
define("_WEEK_AGO","week");
define("_WEEKS_AGO","weeks");
define("_MONTH_AGO","month");
define("_MONTHS_AGO","months");
define("_YEAR_AGO","year");
define("_YEARS_AGO","years");
define("_JUST_NOW","Just now");
define("_HOUR_AGO","hour");
define("_MINUTE_AGO","minute");
define("_About","About");
define("_STUDIES","Studies");
define("_WORKING","Working");
define("_AT","at");
define("_LIVES_IN","Lives in");
define("_BORN_0N","Born on");
define("_SEE_THIS","Only you can see this");
define("_YOUR_FOLLOWER","Your followers");
define("_FOLLOWERS_TITLE","followers");
define("_PEOPLE_WHO_YOU_R_FOLLOWING","People who you are following");
define("_HE","he");
define("_SHE","she");
define("_PEOPLE_THAT","People that");
define("_ARE_FOLLOWING","are following");
define("_YOU_HAVE_NOT_POSTING_ANYTHING","You have not posted anything yet");
define("_YOU_HAVE_NOT_POSTING_ANYTHING_IMAGE","You have not posted anything image yet");
define("_YOU_HAVE_NOT_POSTING_ANYTHING_VIDEO","You have not posted anything video yet");
define("_YOU_HAVE_NOT_POSTING_ANYTHING_AUDIO","You have not posted anything audio yet");
define("_HAS_NOT_POSTED_ANYTHING","has not posted anything yet");
define("_HAS_NOT_POSTED_ANYTHING_IMAGE","has not posted anything image yet");
define("_HAS_NOT_POSTED_ANYTHING_VIDEO","has not posted anything video yet");
define("_HAS_NOT_POSTED_ANYTHING_AUDIO","has not posted anything audio yet");
define("_SORRY_THIS_PAGE_NOT_AVAILABLE","Sorry, This page isn\'t available");
define("_PROFILE_PAGE_NOT_FOUND","Sorry this page may have been removed, or that page doesn\'t exist!");
define("_GO_BACK_PREVIOUS_PAGE","Go back to the previous page");
define("_navbar_ph","Search..");
define("_PUBLIC_POSTS","Public posts'");
define("_ADVANCED_POSTS","Advanced search");
define("_SEARCH_MORE_ABOUT","Search more about");
define("_NOT_FOUND","Not found");
define("_NO_USERS_LIKE_THE_NAME_YOU_ENTERED","No users like the name you entered");
define("_Notification","Notifications");
define("_NO_NOTIFICATIONS","No notifications");
define("_SEE_ALL","See all");
define("_MESSAGES","Messages");
define("_SELET_TO_CHAT","Please select a chat to start messaging");
define("_WRITE_MESSAGE","Write a message..");
define("_USER_PROFILE","User profile");
define("_CURRENT_PASSWORD_INCORRECT","Current password is incorrect");
define("_PLZ_FILL_REQURIED_FIELDS","Please fill required fields");
define("_NEW_PASSWORD_NOT_MATCH","New password field doesn\'t match the confirm field");
define("_CHANGE_PASSWORD_SAVE","changes saved seccessfully");
define("_ERROR_SOMTHING_WORNG","Error, An error occurred! Please try again later.");
define("_GENERAL","General");
define("_EDUCATION","Education");
define("_WORK","Work");
define("_CONTRY","Country");
define("_SELECT_COUNTRY","Select your country");
define("_BIRTHDAY","Birthday");
define("_WEBSITE","Website");
define("_CURRENT_PASSWORD","Current password");
define("_SAVE_CHANGE","Save changes");
define("_FULL_NAME","Full name");
define("_REQURIED","required");
define("_EMAIL_ADDRESS","Email Address");
define("_NEW_PASSWORD","New password");
define("_CONFIRM_NEW_PASSWORD","Confirm new password");
define("_GENDER","Gender");
define("_DELET","Delete");
define("_NOTPAD_MAIN_TITLE","Save your secret password, codes, notes, links and everything online .. just you can view or edit it");
define("_NEW_NOTE_P","Create new secret note, Only you can see and edit it");
define("_NOTE_TITLE","Note title");
define("_NOTE_CONTENT","Note content");
define("_CREATE","create");
define("_ALL_POST_SAVED","All posts that you saved");
define("_NOTHING_SAVED_YET","Nothing saved yet");
define("_CLICK_TO_VIEW_YOUR_REPORT","Click to view your report");
define("_YOUR_REPORT","Your report");
define("_HELP_US_TO_MAKE_OUR_COMMUNITY","Help us to make our community better");
define("_YOUR_FEEDBACK_HELPS_US_IMPROVE_OUR_COMMUNITY","Your feedback helps us improve our community");
define("_SUBJECT","Subject");
define("_SUBMIT","Submit");
define("_REPLAY","Replay");
define("_THIS_PAGE_NOT_AVAILABLE","Sorry, This page isn\'t available'");
define("_THIS_PAGE_NOT_AVAILABLE2","Sorry this page may have been removed, or that page doesn\'t exist!");
define("_THIS_PAGE_NOT_AVAILABLE3","Go back to the previous page");
define("_OPEN","Open");
define("_CLOSED","Closed");
define("_YOU_ANONYMOUSLY_REPORTED","You anonymously reported a");
define("_POST","Post");
define("_UPLOAD","Upload");
define("_HASHTAG_NOT_AVAILABLE","Hashtag not available!");
define("_NEWS","News");
define("_tv","Tv");
define("_STORE","Store");
define("_NEW","New");
define("_JOB","Job");
define("_WORK_TITLE","Work title");
define("_WORK_PLACE","Work place");
define("_COMMENT_ON_THIS_POST","Comment on this post.");
define("_ERROR_POST_1","This post should not to be less than 15 characters.");
define("_ERROR_POST_2","Please select an image and then try again!");
define("_ERROR_VIDEO_POST_2","Please select an video and then try again!");
define("_ERROR_AUDIO_POST_2","Please select an Audio and then try again!");
define("_ERROR_POST_3","Your image must be less than 100MB of size.");
define("_ERROR_POST_4","Your image was not jpeg, jpg, or png file.");
define("_ERROR_VIDEO_POST_4","Your video was not mp4, mp3, avi, 3gp, mov, mpeg,webm,flv,mkv file.");
define("_ERROR_AUDIO_POST_4","Your video was not  mp3 file.");
define("_ERROR_POST_5","An error occured while processing the image. Try again.");
define("_ERROR_AUDIO_POST_5","An error occured while processing the audio. Try again.");
define("_ERROR_VIDEO_POST_5","An error occured while processing the video. Try again.");
define("_ERROR_POST_6","ERROR: photo not uploaded. Try again.");
define("_ERROR_VIDEO_POST_6","ERROR: video not uploaded. Try again.");
define("_ERROR_AUDIO_POST_6","ERROR: audio not uploaded. Try again.");
?>